### ISSUE TITLE
code not working

### ISSUE THREAD

**Issue by ashokshejwal** [mortezamg63/Adaptive-Median-Filter#2]
Sir,

I tried your code with the sample image provided by you of noisy board. On running the code, it is not giving desired result. Noisy image is getting copied side by side 3 times instead of enhanced image. Kindly run the code and see your self. kindly provide the correction.

**Comment by mortezamg63** [comment]
Hi
Thanks for your hint. I checked the code, but there was no mistake. For purpose of clarification, I am showing the process step by step in the following.
At first, pay attention to the following notes:
1- your image must be a gray scale image. Perhaps, you copied the image from my github page. Because the image in the page is degraded, using the image for test is not appropriate because it will show the copied image instead of enhanced one.
2- you must add salt and pepper noise to the imported image in matlab program. 
The source code till now is :
img=imread('testimage.jpg');
img=rgb2gray(img);
noisyimg1=imnoise(img, 'salt & pepper', 0.5)
noisyimg2 = imnoise(img, 'salt & pepper', 0.7)

As you can see I created two different noisy images. Now the original image and two noisy images are shown below.

## input image

![image](https://user-images.githubusercontent.com/15813546/43679615-380196ac-983d-11e8-8596-84beda15122c.png)

## noisyimg1

![image](https://user-images.githubusercontent.com/15813546/43679625-5a75e602-983d-11e8-9ad4-63b99833cc4f.png)

## noisyimg2

![image](https://user-images.githubusercontent.com/15813546/43679627-60b55c1e-983d-11e8-8b12-640a49eedb8f.png)

Finally the following code is used to reduce the noise:

#### Adaptive_Median_filter(noisyimg1,13)

![image](https://user-images.githubusercontent.com/15813546/43679635-8c5b2362-983d-11e8-9e25-3534a51b0c2e.png)

#### Adaptive_Median_filter(noisyimg2,13)

![image](https://user-images.githubusercontent.com/15813546/43679642-a537a0b8-983d-11e8-8e43-b1c6bac0f11c.png)
